project_id = "sywgjwxtuijrdmekxquj"

[functions.add-entry]
verify_jwt = false

[functions.fetch-ical]
verify_jwt = false

[functions.fetch-weather]
verify_jwt = false

[functions.timer-status]
verify_jwt = false
